### ISSUE TITLE
name of the ec-2 isntance is "-0"

### ISSUE THREAD

**Issue by sancha18** [clouddrove/terraform-aws-ec2#13]
Can't set name for the instance using terraform 0.12.7 with terragrunt 0.28.18
my terragrunt.hcl:

`terraform {
              
 source = "git::git@github.com:clouddrove/terraform-aws-ec2.git?ref=0.12.8"

}

include {
  path = find_in_parent_folders()
}

dependencies {
  paths = ["../aws-data","../spell-vpc", "../spell-sec2"]
}

dependency "aws-data" {
  config_path = "../aws-data"
}

dependency "spell-vpc" {
  config_path = "../spell-vpc"
}

dependency "spell-sec1" {
  config_path = "../spell-sec1"
}

###########################################################
# View all available inputs for this module:
# https://registry.terraform.io/modules/clouddrove/ec2/aws/0.12.8?tab=inputs
###########################################################
inputs = {

  # Name to be used on all resources as prefix
  # type: string
  #key_name = "test1"
  name = "server1"

  # ID of AMI to use for the instance
  # type: string
  ami = dependency.aws-data.outputs.ubuntu_1804_aws_ami_id

  # The type of instance to start
  # type: string
  instance_type = "t3.small"

  #Description: ManagedBy, eg 'CloudDrove' or 'AnmolNagpal'.
  managedby = "Test"

  #Description: Associate a public IP address with the instance.
  associate_public_ip_address = true
  
  #Description: A list of VPC Subnet IDs to launch in.
  subnet_ids = dependency.spell-vpc.outputs.public_subnets

  #Description: A list of security group IDs to associate with.
  vpc_security_group_ids_list = [dependency.spell-sec1.outputs.this_security_group_id]
  
  #Description: A list of security group IDs to associate with.
  assign_eip_address = true
  
  #Description: The tenancy of the instance (if the instance is running in a VPC). 
  #An instance with a tenancy of dedicated runs on single-tenant hardware. 
  #The host tenancy is not supported for the import-instance command.
  tenancy = "default"

  #Description: Size of the root volume in gigabytes.
  disk_size = 20
  
}
`

my outpus:
`
...
 # aws_instance.default[0] will be created
  + resource "aws_instance" "default" {
      + ami                          = "ami-0d9d9a0444a6ed5c8"
      + arn                          = (known after apply)
      + associate_public_ip_address  = true
      + availability_zone            = (known after apply)
      + cpu_core_count               = (known after apply)
      + cpu_threads_per_core         = (known after apply)
      + disable_api_termination      = false
      + ebs_optimized                = false
      + get_password_data            = false
      + host_id                      = (known after apply)
      + id                           = (known after apply)
      + instance_state               = (known after apply)
      + instance_type                = "t3.small"
      + ipv6_address_count           = 0
      + ipv6_addresses               = []
      + key_name                     = (known after apply)
      + monitoring                   = false
      + outpost_arn                  = (known after apply)
      + password_data                = (known after apply)
      + placement_group              = (known after apply)
      + primary_network_interface_id = (known after apply)
      + private_dns                  = (known after apply)
      + private_ip                   = (known after apply)
      + public_dns                   = (known after apply)
      + public_ip                    = (known after apply)
      + secondary_private_ips        = (known after apply)
      + security_groups              = (known after apply)
      + source_dest_check            = true
      + subnet_id                    = "subnet-0bd6eea615017c16c"
      + tags                         = {
          + "Application" = ""
          + "CreatedBy"   = "terraform"
          + "Environment" = ""
          + "ManagedBy"   = "test"
          + "Name"        = "-0"
        }
      + tenancy                      = "default"
      + volume_tags                  = {
          + "Application" = ""
          + "CreatedBy"   = "terraform"
          + "Environment" = ""
          + "ManagedBy"   = "test"
          + "Name"        = "-0"
        }
...
`

**Comment by sohanyadav** [comment]
@sancha18  this is from labels  you should  add name and env in example file 
just like this 
  n```
ame        = "ec2-instance"
  application = "clouddrove"
  environment = "test"
  label_order = ["environment", "application", "name"]
```
