### ISSUE TITLE
change value for tag managedby 

### ISSUE THREAD

**Issue by my-janala** [clouddrove/terraform-aws-ec2#4]
Hi, I have used this ec2 and it works very well. I have an issue though. The module uses another module https://github.com/clouddrove/terraform-labels/blob/master/variables.tf and it has a variable 

```variable "managedby" {
  type        = string
  default     = "anmol@clouddrove.com"
  description = "ManagedBy, eg 'CloudDrove' or 'AnmolNagpal'."
}
```

How would it change the value of  **managedby** to something like my name or team?

**Comment by my-janala** [comment]
Hi @anmolnagpal , many thanks for attempting to fix this as an enhancement. However, this same issue persisted on your other terraform repos such as https://github.com/clouddrove/terraform-aws-security-group/blob/master/main.tf. 

Wouldn't it be also necessary to fix the issue here https://github.com/clouddrove/terraform-labels/blob/master/variables.tf 

`variable "managedby" {
  type        = string
  default     = "anmol@clouddrove.com"
  description = "ManagedBy, eg 'CloudDrove' or 'AnmolNagpal'."
}`

**Comment by anmolnagpal** [comment]
Hello @my-janala 

Ec2, have been fixed other modules are on the way will be fixed today.

Thanks 
Anmol
