### ISSUE TITLE
Output for Public IP is empty

### ISSUE THREAD

**Issue by MartinCanovas** [clouddrove/terraform-aws-ec2#9]
### Expected Behavior
Output for Public IP returns a public IP address.

### Steps to Reproduce
module "instance" {
source = "git::https://github.com/clouddrove/terraform-aws-ec2.git?ref=tags/0.12.6"
key_name = var.ssh_key_pair
instance_type = var.ec2
instance_count = 1
tenancy = "default"
ami = var.ami
disk_size = 10
ebs_optimized = false
ebs_volume_type = "gp2"
assign_eip_address = false
associate_public_ip_address = true
vpc_security_group_ids_list = [aws_security_group.sg_instance.id]
subnet_ids = [lookup(module.public_subnets.az_subnet_ids, var.az1)]
application = "app"
managedby = "terraform"
name = "app"
environment = var.stage
label_order = ["environment", "name"]
instance_tags = var.instance_tags
}

output "instance_public_ip" {
value = module.instance.public_ip
}

### Environment:

OS: MacOS 10.15.6
terraform providers --version
Terraform v0.12.26
provider.aws v2.70.0
provider.local v1.4.0
provider.null v2.1.2
provider.template v2.1.2

**Comment by sohanyadav** [comment]
@MartinCanovas, 
your output value is wrong this should be 
`output "instance_public_ip" {
  value       = module.ec2.*.public_ip
}
` 
Check output Screenshot 

![Screenshot from 2020-11-03 15-31-13](https://user-images.githubusercontent.com/31764946/97972153-1cf05f80-1dea-11eb-8c23-2ec6f1d3c9ff.png)
